# This file was generated by GoReleaser. DO NOT EDIT.
cask "malt" do
  version "0.11.3"

  on_macos do
    sha256 "bb1658d87db23d10481e371ff4b4135e8afabe26ca7a7993be634d239f7a2f2a"
    url "https://github.com/indaco/malt/releases/download/v#{version}/malt_#{version}_darwin_all.tar.gz"
  end

  name "malt"
  desc "A fast, Homebrew-compatible package manager for macOS"
  homepage "https://github.com/indaco/malt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "malt"
  binary "mt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/malt"]
    end
  end

  # No zap stanza required

end
