# This file was generated by GoReleaser. DO NOT EDIT.
cask "malt" do
  version "0.11.1"

  on_macos do
    sha256 "01b288adf31802ae8374dbe36e77c9fa33f24a786c2643b51b18c037092e1229"
    url "https://github.com/indaco/malt/releases/download/v#{version}/malt_#{version}_darwin_all.tar.gz"
  end

  name "malt"
  desc "A fast, Homebrew-compatible package manager for macOS"
  homepage "https://github.com/indaco/malt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "malt"
  binary "mt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/malt"]
    end
  end

  # No zap stanza required

end
