# This file was generated by GoReleaser. DO NOT EDIT.
cask "malt" do
  version "0.6.1"

  on_macos do
    url "https://github.com/indaco/malt/releases/download/v#{version}/malt_#{version}_darwin_all.tar.gz"
    sha256 "4a243f067ab2b7da3b965c2f47672031552f59c6498c7b792a8f0c19c120568a"
  end

  name "malt"
  desc "A fast, Homebrew-compatible package manager for macOS"
  homepage "https://github.com/indaco/malt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "malt"
  binary "mt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/malt"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mt"]
    end
  end

  # No zap stanza required

end
