# This file was generated by GoReleaser. DO NOT EDIT.
cask "sley" do
  name "sley"
  desc "CLI for semantic versioning using a simple .version file. Language-agnostic with plugins for git tagging, changelog generation, versioning policies and more."
  homepage "https://github.com/indaco/sley"
  version "0.11.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sley"

  on_macos do
    on_intel do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Darwin_x86_64.tar.gz"
      sha256 "eafd6e01cf7a186279d4305d50c2a6a5b7d59acbf497793bcb15d8b5ca31f5cc"
    end
    on_arm do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Darwin_arm64.tar.gz"
      sha256 "51172cd1a8387fdc956b8c99135f2e2012802c81f33405161fc8f95785177453"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Linux_x86_64.tar.gz"
      sha256 "7094e5c851e8f99f92e53ef5e5481dbc86deace28734989f8c08f929b2a5c438"
    end
    on_arm do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Linux_arm64.tar.gz"
      sha256 "63ab18f6c901461d2d0d7bcd1b88524c02893d84c97befe9f94e674d474b41cd"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sley"]
    end
  end

  # No zap stanza required
end
