# This file was generated by GoReleaser. DO NOT EDIT.
cask "sley" do
  version "0.13.2"

  on_macos do
    on_intel do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Darwin_x86_64.tar.gz"
      sha256 "319dfd57e418e06896c10d6e2a35f84ee5c686f8074bb7e2ed469e5fbe41e31b"
    end
    on_arm do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Darwin_arm64.tar.gz"
      sha256 "1bc15d7f79940ad58f9c94782ceed82650a4c728af524283e21455b24badfe6f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Linux_x86_64.tar.gz"
      sha256 "a7156333b99d43e589a32174cbfc5ef2266afc01d4dddf5a9ac8e0ab4b652705"
    end
    on_arm do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Linux_arm64.tar.gz"
      sha256 "599b1be8be832c6b12ec27d8e7bddece0bf9c7cc2fd8b11b4654ca3bf43b4f3e"
    end
  end

  name "sley"
  desc "CLI for semantic versioning using a simple .version file. Language-agnostic with plugins for git tagging, changelog generation, versioning policies and more."
  homepage "https://github.com/indaco/sley"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sley"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sley"]
    end
  end

  # No zap stanza required

end
