# This file was generated by GoReleaser. DO NOT EDIT.
cask "sley" do
  name "sley"
  desc "CLI for semantic versioning using a simple .version file. Language-agnostic with plugins for git tagging, changelog generation, versioning policies and more."
  homepage "https://github.com/indaco/sley"
  version "0.8.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sley"

  on_macos do
    on_intel do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Darwin_x86_64.tar.gz"
      sha256 "c5171ba9fe0899607888ce1a15916a1fa5e1b725691db67b351c845fe4fb96c0"
    end
    on_arm do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Darwin_arm64.tar.gz"
      sha256 "3acd368230eb61cc34534945e58131607861d28bf50dfe712450d8638719bf3b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Linux_x86_64.tar.gz"
      sha256 "68233329d69074038255778e86dea80026ba4aa9d825efa68b4ed3945b2485cf"
    end
    on_arm do
      url "https://github.com/indaco/sley/releases/download/v#{version}/sley_Linux_arm64.tar.gz"
      sha256 "61dd8200ceb69ec70c02d8a6e4d4eaca04c18c828186875fcdf8001a32999dce"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sley"]
    end
  end

  # No zap stanza required
end
