# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sley < Formula
  desc "A CLI tool for managing semantic versioning using a .version file"
  homepage "https://github.com/indaco/sley"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/indaco/sley/releases/download/v0.6.0/sley_Darwin_x86_64.tar.gz"
      sha256 "c8140198099eac06a2d66587c2726ab0e19bacf04c920960ced9bb84c8f20ba2"

      def install
        bin.install "sley"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/indaco/sley/releases/download/v0.6.0/sley_Darwin_arm64.tar.gz"
      sha256 "02a1518c82b9fd6f6d1c946fca7583256791d802ac57bcd2c83e9fb989cc34ca"

      def install
        bin.install "sley"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/indaco/sley/releases/download/v0.6.0/sley_Linux_x86_64.tar.gz"
      sha256 "80d961583ee60f99f649c2f85535b6ecfc8a117a6113e966104f61715218003f"
      def install
        bin.install "sley"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/indaco/sley/releases/download/v0.6.0/sley_Linux_arm64.tar.gz"
      sha256 "c5f809813142ad01abc3fd5dbe037c35dbed9ed38058eb7ada48773e5a943180"
      def install
        bin.install "sley"
      end
    end
  end

  test do
    system "#{bin}/sley", "--version"
  end
end
