# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tempo < Formula
  desc "A CLI tool for managing assets and scaffolding components in [templ](https://templ.guide)-based projects"
  homepage "https://github.com/indaco/tempo"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/indaco/tempo/releases/download/v0.3.0/tempo_Darwin_x86_64.tar.gz"
      sha256 "fb0eecf8a0bc9e07ff3a9eb8a0311f075eef5fd66011280d0bb09c917cc5a8dc"

      def install
        bin.install "tempo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/indaco/tempo/releases/download/v0.3.0/tempo_Darwin_arm64.tar.gz"
      sha256 "46a8a4b10205336b694598771ef8a43edb9cd15462049972c6754c0129eb00ab"

      def install
        bin.install "tempo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/indaco/tempo/releases/download/v0.3.0/tempo_Linux_x86_64.tar.gz"
      sha256 "68519c72e0a4f5c9d7197552bdf6d8669f50afb9d0b14db2a9349f859042df08"
      def install
        bin.install "tempo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/indaco/tempo/releases/download/v0.3.0/tempo_Linux_arm64.tar.gz"
      sha256 "13e96510db781681b44eab7878408e0374c30ff6b4c86387aad275f99e79fd6d"
      def install
        bin.install "tempo"
      end
    end
  end

  test do
    system "#{bin}/tempo", "--version"
  end
end
